efs/urls.py
from django.contrib import admin
from django.conf.urls import  include,url
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('accounts/', include('accounts.urls')),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    #path('accounts/login', auth_views.LoginView.as_view(), name='login'),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    path('', include('django.contrib.auth.urls')) ,
]

portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
path('stock_list', views.stock_list, name='stock_list'),
path('stock/create/', views.stock_new, name='stock_new'),
path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
path('investment_list', views.investment_list, name='investment_list'),
path('investment/create/', views.investment_new, name='investment_new'),
path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
path('cutomer/create/', views.customer_new, name='customer_new'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    url(r'^customers_json/', views.CustomerList.as_view()),
path('download_pdf/<int:pk>', views.download_pdf, name='download_pdf'),
path('mutualfund_list', views.mutualfund_list, name='mutualfund_list'),
path('mutualfund/create/', views.mutualfund_new, name='mutualfund_new'),
path('mutualfund/<int:pk>/edit/', views.mutualfund_edit, name='mutualfund_edit'),
path('mutualfund/<int:pk>/delete/', views.mutualfund_delete, name='mutualfund_delete'),
path('viewgraph/', views.portfolio_piechart, name='portfolio_piechart'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value

class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField (max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price


    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol='
        api_key = '&interval=1min&apikey=0UW1QFLODU5QOVEO'
        url = main_api + symbol_f + api_key
        json_data = requests.get(url).json()
        open_price = float(json_data["Global Quote"]["02. open"])
        #open_price=3900
        share_value = open_price
        return share_value



    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)



class MutualFund(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='mutualfund')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_mutualfund(self):
        return self.recent_value - self.acquired_value

portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment,MutualFund

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)
class StockForm(forms.ModelForm):
   class Meta:
       model = Stock
       fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)

class InvestmentForm(forms.ModelForm):
   class Meta:
       model = Investment
       fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date',)


class MutualFundForm(forms.ModelForm):
   class Meta:
       model = MutualFund
       fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date',)

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from django.core.mail import EmailMessage
from django.template.loader import get_template
from io import BytesIO
from io import StringIO  ## for Python 3
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from efs import settings
from xhtml2pdf import pisa
from django.http import HttpResponse
from django.views.generic import View
from .utils import render_to_pdf
from efs import settings
from django.shortcuts import render
import random
import datetime
import time

now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

@login_required
def customer_list(request):

    #send_mail('Example Subject', 'Example message', 'jdyesh@gmail.com', ['yesh080690@gmail.com'])
    customer = Customer.objects.filter(created_date__lte=timezone.now())

    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})

@login_required
def customer_new(request):
   if request.method == "POST":
       form = CustomerForm(request.POST)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
       form = CustomerForm()
       # print("Else")
   return render(request, 'portfolio/customer_new.html', {'form': form})



@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')


@login_required
def stock_list(request):
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})

@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   return redirect('portfolio:stock_list')



@login_required
def investment_list(request):
   investment = Investment.objects.filter(acquired_date__lte=timezone.now())
   return render(request, 'portfolio/investment_list.html', {'investment': investment})

@login_required
def investment_new(request):
   if request.method == "POST":
       form = InvestmentForm(request.POST)
       if form.is_valid():
           investment = form.save(commit=False)
           investment.recent_date_date = timezone.now()
           investment.save()
           investment = Investment.objects.filter()
           return render(request, 'portfolio/investment_list.html',
                         {'investment': investment})
   else:
       form = InvestmentForm()
       # print("Else")
   return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_edit(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   if request.method == "POST":
       form = InvestmentForm(request.POST, instance=investment)
       if form.is_valid():
           investment = form.save()
           # stock.customer = stock.id
           investment.updated_date = timezone.now()
           investment.save()
           investment = Investment.objects.filter(acquired_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html', {'investment': investment})
   else:
       # print("else")
       form = InvestmentForm(instance=investment)
   return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   investment.delete()
   return redirect('portfolio:investment_list')


@login_required
def portfolio(request,pk):
   customer = get_object_or_404(Customer, pk=pk)
   customers = Customer.objects.filter(created_date__lte=timezone.now())
   investments =Investment.objects.filter(customer=pk)
   stocks = Stock.objects.filter(customer=pk)
   mutualfund = MutualFund.objects.filter(customer=pk)
   #sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
   sum_recent_value = Investment.objects.filter(customer=pk).aggregate(recent_sum=Sum('recent_value'))['recent_sum']
   #sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
   sum_acquired_value = Investment.objects.filter(customer=pk ).aggregate(acquired_sum=Sum('acquired_value'))['acquired_sum']
   sum_acquired_value_mf = MutualFund.objects.filter(customer=pk).aggregate(acquired_sum=Sum('acquired_value'))['acquired_sum']
   sum_recent_value_mf = MutualFund.objects.filter(customer=pk).aggregate(recent_sum=Sum('recent_value'))['recent_sum']

   #overall_investment_results = sum_recent_value-sum_acquired_value
   # Initialize the value of the stocks
   sum_current_stocks_value = 0
   sum_of_initial_stock_value = 0

   # Loop through each stock and add the value to the total
   for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()
   portfolio_initial_investments = float(sum_of_initial_stock_value) + float(sum_acquired_value) + float(
       sum_acquired_value_mf)
   portfolio_current_investments = float(sum_current_stocks_value) + float(sum_recent_value) + float(
       sum_recent_value_mf)
   url = "https://openexchangerates.org/api/latest.json?app_id="
   app_id = settings.OPENEXCHANGE_APP_ID
   additional = "&base=USD"
   main_url = url + app_id + additional
   json_data = requests.get(main_url).json()
   value = json_data.get('rates')
   new_currency = value.get('INR')
   INR_inital_value=new_currency * portfolio_initial_investments
   INR_current_value=new_currency * portfolio_current_investments

   print(INR_inital_value)

   return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                       'customer': customer,
                                                       'investments': investments,
                                                       'stocks': stocks,
                                                       'mutualfund':mutualfund,
                                                       'sum_acquired_value': sum_acquired_value,
                                                       'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                       'portfolio_initial_investments': portfolio_initial_investments,
                                                       'portfolio_current_investments': portfolio_current_investments,
                                                       'sum_acquired_value_mf':sum_acquired_value_mf,
                                                       'sum_recent_value_mf':sum_recent_value_mf,
                                                       'INR_inital_value':INR_inital_value,
                                                       'INR_current_value':INR_current_value


                                                       })


# Lists all customers
class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<body>

<body>
<style>

        body {
            background-color: beige;
        }
</style>

  <header class="jumbotron my-4 table-responsive" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>

<div class="row"><br>

    <h2 style="padding-left: 15Px"><u>Customer Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr bgcolor="white">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="4">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr bgcolor="white">
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                     <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a></td>


                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
<div class="row">
            <a href="{% url 'portfolio:customer_new' %}" class="row"><span
                    class="btn btn-primary">Add Customer</span></a>
        </div>

</body>
</html>

{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html lang="en">
    <body>

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
  <header class="jumbotron my-4 table-responsive" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>
    <div class="row">
        <h2 style="padding-left: 15Px"><u>Investment Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr bgcolor="white">
                <th>Customer number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for investment in investment %}
                <tr bgcolor="white">
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date }}</td>
                    <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                    class="btn btn-primary">Add Investment</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/mutualfund_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html lang="en">
    <body>

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
  <header class="jumbotron my-4 table-responsive" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>
    <div class="row">
        <h2 style="padding-left: 15Px"><u>Mutual Fund Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr bgcolor="white">
                <th>Customer number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for mutualfund in mutualfund %}
                <tr bgcolor="white">
                    <td>{{ mutualfund.customer }}</td>
                    <td>{{ mutualfund.category }}</td>
                    <td>{{ mutualfund.description }}</td>
                    <td>{{ mutualfund.acquired_value }}</td>
                    <td>{{ mutualfund.acquired_date }}</td>
                    <td>{{ mutualfund.recent_value }}</td>
                    <td>{{ mutualfund.recent_date }}</td>
                    <td><a href="{% url 'portfolio:mutualfund_edit' pk=mutualfund.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:mutualfund_delete' pk=mutualfund.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:mutualfund_new' %}" class="row"><span
                    class="btn btn-primary">Add Mutual Fund</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load mathfilters %}
{% load humanize %}

{% block content %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <meta charset="UTF-8">
    <title>Eagle Financial Services</title>
</head>
<body>
 <header class="jumbotron my-4 table-responsive" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>
<div class="row">
 <a syle="text-align:right;" href="{% url 'portfolio:download_pdf' pk=customer.pk%}">Download and Email Report</a>
</div>


<div class="row">
    <h1> Customer Portfolio</h1>
</div>
    <h1 class="navbar-brand" style="padding-left: 15Px">Customer Investment -piechart </h1>

 <div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
 </div>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script><script>
    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: [{{sum_current_stocks_value|sub:sum_of_initial_stock_value}},{{sum_recent_value_mf|sub:sum_acquired_value_mf}}, {{sum_recent_value|sub:sum_acquired_value}}],
          backgroundColor: [
            '#ff0000', '#0000ff', '#ff0080'],
          label: 'Portfolio'
        }],
        labels: ['Stocks', 'Mutual Fund', 'Investment']
      },
      options: {
        responsive: true
      }
    };
 
    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };
  </script>


<div class="row">
    <h2 class="navbar-brand" style="padding-left: 15Px">Overall Portfolio Performance</h2>
</div>

<div >
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Portfolio Initial Investments -USD</th>
            <th>Portfolio Initial Investments -INR</th>
            <th>Portfolio Current Investments-USD</th>
            <th>Portfolio Current Investments -INR</th>
            <th>Grand Total Results -USD</th>
            <th>Grand Total Results -INR</th>

        </tr>

        </thead>
        <tbody>
            <tr>
                <td>{{ portfolio_initial_investments|intcomma }}</td>
                <td>{{ INR_inital_value|intcomma }}</td>
                <td>{{ portfolio_current_investments|intcomma }}</td>
                <td>{{ INR_current_value|intcomma }}</td>
                <td>{{ portfolio_current_investments|sub:portfolio_initial_investments|intcomma  }}</td>
                <td>{{ INR_current_value|sub:INR_inital_value|intcomma  }}</td>

            </tr>
        </tbody>
    </table>
</div>


<div class="row">
    <h2 class="navbar-brand" style="padding-left: 15Px">Stocks Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Initial Stock Price USD</th>
            <th>Initial Stock Value</th>
            <th>Current Stock Price</th>
            <th>Current Stock Value</th>
            <th>Results</th>
        </tr>
        </thead>
        <tbody>
   {% for stock in stocks %}
            <tr>
                <td>{{ stock.customer }}</td>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.name }}</td>
                <td>{{ stock.shares|intcomma }}</td>
                <td>{{ stock.purchase_price|intcomma }}</td>
                <td>{{ stock.initial_stock_value|intcomma}}
                <td>{{ stock.current_stock_price|intcomma}}
                <td>{{ stock.current_stock_value|intcomma}}
                <td>{{ stock.current_stock_value|sub:stock.initial_stock_value }}</td>


            </tr>
        {% endfor %}
        </tbody>
    </table>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Stocks</th>
            <th>Total of Current Stocks</th>
            <th>Results</th>


        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{  sum_current_stocks_value }}</td>
                <td>{{ sum_of_initial_stock_value}}</td>
                <td>{{ sum_current_stocks_value|sub:sum_of_initial_stock_value }}</td>


            </tr>
        </tbody>
    </table>
</div>
</div>


<div class="row">
    <h2 style="padding-left: 15Px">Investments Information</h2>
</div>
<div >
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Category</th>
            <th>Description</th>
            <th>Acquired Value</th>
            <th>Acquired Date</th>
            <th>Recent Value</th>
            <th>Recent Date</th>
            <th>Results</th>

        </tr>
        </thead>
        <tbody>
        {% for investment in investments %}
            <tr>
                <td>{{ investment.customer }}</td>
                <td>{{ investment.category }}</td>
                <td>{{ investment.description }}</td>
                <td>{{ investment.acquired_value }}</td>
                <td>{{ investment.acquired_date }}</td>
                <td>{{ investment.recent_value }}</td>
                <td>{{ investment.recent_date }}</td>
                <td>{{ investment.recent_value|sub:investment.acquired_value }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Investments</th>
            <th>Total of Current Investments</th>
            <th>Results</th>


        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sum_acquired_value }}</td>
                <td>{{ sum_recent_value}}</td>
                <td>{{ sum_recent_value|sub:sum_acquired_value }}</td>




            </tr>
        </tbody>
    </table>
</div>
</div>


<div class="row">
    <h2 style="padding-left: 15Px">Mutual Fund Information</h2>
</div>
<div >
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Category</th>
            <th>Description</th>
            <th>Acquired Value</th>
            <th>Acquired Date</th>
            <th>Recent Value</th>
            <th>Recent Date</th>
            <th>Results</th>

        </tr>
        </thead>
        <tbody>
        {% for mutualfund in mutualfund %}
            <tr>
                <td>{{ mutualfund.customer }}</td>
                <td>{{ mutualfund.category }}</td>
                <td>{{ mutualfund.description }}</td>
                <td>{{ mutualfund.acquired_value }}</td>
                <td>{{ mutualfund.acquired_date }}</td>
                <td>{{ mutualfund.recent_value }}</td>
                <td>{{ mutualfund.recent_date }}</td>
                <td>{{ mutualfund.recent_value|sub:mutualfund.acquired_value}}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>sum_acquired_value_mf</th>
            <th>sum_recent_value_mf</th>
            <th>Results</th>


        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sum_acquired_value_mf }}</td>
                <td>{{ sum_recent_value_mf}}</td>
                <td>{{ sum_recent_value_mf|sub:sum_acquired_value_mf }}</td>




            </tr>
        </tbody>
    </table>
</div>
</div>


</body>

{% endblock %}